# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-10 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=100)),
                ('infinite', models.BooleanField(default=False)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Ingredient')),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.UserAccount')),
            ],
        ),
        migrations.AddField(
            model_name='useraccount',
            name='ingredients',
            field=models.ManyToManyField(through='main.UserIngredient', to='main.Ingredient'),
        ),
    ]
