# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-15 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20161111_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='average_rating',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='rating_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
