# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-11 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_useraccount_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='none', upload_to=b'images'),
            preserve_default=False,
        ),
    ]
