# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 20:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20161213_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeimage',
            name='recipe',
        ),
        migrations.AddField(
            model_name='recipeimage',
            name='user_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.UserAccount'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipeimage',
            name='image',
            field=models.ImageField(upload_to=b'userimages'),
        ),
    ]
