# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-20 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20161213_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatedRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_rating', models.IntegerField(null=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Recipe')),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.UserAccount')),
            ],
        ),
        migrations.AlterField(
            model_name='recipeimage',
            name='image',
            field=models.ImageField(upload_to='recipeimages'),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='image',
            field=models.ImageField(upload_to='userimages'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='recipe_ratings',
            field=models.ManyToManyField(related_name='useraccount_ratings', through='main.RatedRecipe', to='main.Recipe'),
        ),
    ]
