# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-29 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20161220_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit_short',
            field=models.CharField(max_length=20),
        ),
    ]
